<?php
$members = [
    [
        'first_name'       => 'Stacy',
        'last_name'        => 'Harper',
        'email'            => 'tilypoquh@mailinator.com',
        'password'         => '##ALNEE#DLI)wZHvOp14A8Tp',
        'member_type'      => 'member',
        'membership_level' => 'basic',
    ],
    [
        'first_name'       => 'Tucker',
        'last_name'        => 'Copeland',
        'email'            => 'sicuzymyt@mailinator.com',
        'password'         => '^$^^6@TyiDpiL72B3rZ7v*tY',
        'member_type'      => 'member',
        'membership_level' => 'premium',
    ],
    [
        'first_name'       => 'Sam',
        'last_name'        => 'Lydard',
        'email'            => 'tryingtoadultrva@gmail.com',
        'password'         => 'bNe#JO#h)uyP30oAdcZkrQfi',
        'member_type'      => 'super_admin',
        'membership_level' => 'premium',
    ],
    [
        'first_name'       => 'Julie',
        'last_name'        => 'Marsh',
        'email'            => 'eippih@gmail.com',
        'password'         => 'a14B%(T*UXk1auRFd)#ZNw)g',
        'member_type'      => 'super_admin',
        'membership_level' => 'premium',
    ],
    [
        'first_name'       => 'Adam',
        'last_name'        => 'Peoples',
        'email'            => 'foreunner1618@gmail.com',
        'password'         => '3grQTvBOODPRtOOQESmS0TXD',
        'member_type'      => 'admin',
        'membership_level' => 'premium',
    ],
    [
        'first_name'       => 'Mariah',
        'last_name'        => 'Payne',
        'email'            => 'mariah.payne831@gmail.com',
        'password'         => '3grQTvBOODPRtOOQESmS0TXD',
        'member_type'      => 'admin',
        'membership_level' => 'premium',
    ],
    [
        'first_name'       => 'Cassidy',
        'last_name'        => 'Ryan',
        'email'            => 'claineryan13@gmail.com',
        'password'         => '^yDYADcss&kcH29yxhdvnJXO',
        'member_type'      => 'volunteer',
        'membership_level' => 'premium',
    ],
    [
        'first_name'       => 'Dana',
        'last_name'        => 'Harrell',
        'email'            => 'dana.p.harrell@gmail.com',
        'password'         => 'b0niD@oMxf9wax@n8*@DIYGH',
        'member_type'      => 'volunteer',
        'membership_level' => 'premium',
    ],
];

for ($i = 1; $i <= 10; $i++) {
    $members[] = [
        'first_name'            => 'Member' . $i,
        'last_name'             => 'Example',
        'email'                 => 'sample_member_' . $i . '@example.com',
        'password'              => 'password',
        'profileimgid'          => 0,
        'joined_at'             => date('Y-m-d H:i:s', strtotime('-' . ($i * 3) . ' days')),
        'address'               => $i . ' Main St - - Richmond - VA - 2323' . $i,
        'phone'                 => '555-000-' . sprintf('%04d', $i),
        'dob'                   => '1990-01-0' . (($i % 9) + 1),
        'member_type'           => 'member',
        'membership_level'      => ($i % 3 === 0) ? 'premium' : (($i % 2) ? 'basic' : 'free'),
        'facebook'              => 'https://facebook.com/member' . $i,
        'linkedin'              => 'https://linkedin.com/in/member' . $i,
        'instagram'             => 'https://instagram.com/member' . $i,
        'twitter'               => 'https://twitter.com/member' . $i,
        'biography'             => 'Sample biography for member ' . $i,
        'notes'                 => '',
        'interests'             => 'Music, Hiking',
        'opt_in_marketing_email'=> 1,
        'opt_in_marketing_sms'  => 0,
        'opt_in_event_email'    => 1,
        'opt_in_event_sms'      => 0,
        'hide_event_attendance' => 0,
    ];
}

return $members;
