<?php
return [
    [
        'ute_id' => 'sample_event_1',
        'name' => 'Sample Event 1',
        'date' => '2025-07-04',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '101 Sample St - - City - ST - 10001',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 1',
    ],
    [
        'ute_id' => 'sample_event_2',
        'name' => 'Sample Event 2',
        'date' => '2025-07-07',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '102 Sample St - - City - ST - 10002',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 2',
    ],
    [
        'ute_id' => 'sample_event_3',
        'name' => 'Sample Event 3',
        'date' => '2025-07-10',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '103 Sample St - - City - ST - 10003',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 3',
    ],
    [
        'ute_id' => 'sample_event_4',
        'name' => 'Sample Event 4',
        'date' => '2025-07-13',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '104 Sample St - - City - ST - 10004',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 4',
    ],
    [
        'ute_id' => 'sample_event_5',
        'name' => 'Sample Event 5',
        'date' => '2025-07-16',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '105 Sample St - - City - ST - 10005',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 5',
    ],
    [
        'ute_id' => 'sample_event_6',
        'name' => 'Sample Event 6',
        'date' => '2025-07-19',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '106 Sample St - - City - ST - 10006',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 6',
    ],
    [
        'ute_id' => 'sample_event_7',
        'name' => 'Sample Event 7',
        'date' => '2025-07-22',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '107 Sample St - - City - ST - 10007',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 7',
    ],
    [
        'ute_id' => 'sample_event_8',
        'name' => 'Sample Event 8',
        'date' => '2025-07-25',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '108 Sample St - - City - ST - 10008',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 8',
    ],
    [
        'ute_id' => 'sample_event_9',
        'name' => 'Sample Event 9',
        'date' => '2025-07-28',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '109 Sample St - - City - ST - 10009',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 9',
    ],
    [
        'ute_id' => 'sample_event_10',
        'name' => 'Sample Event 10',
        'date' => '2025-07-31',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '110 Sample St - - City - ST - 10010',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 10',
    ],
    [
        'ute_id' => 'sample_event_11',
        'name' => 'Sample Event 11',
        'date' => '2025-08-03',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '111 Sample St - - City - ST - 10011',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 11',
    ],
    [
        'ute_id' => 'sample_event_12',
        'name' => 'Sample Event 12',
        'date' => '2025-08-06',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '112 Sample St - - City - ST - 10012',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 12',
    ],
    [
        'ute_id' => 'sample_event_13',
        'name' => 'Sample Event 13',
        'date' => '2025-08-09',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '113 Sample St - - City - ST - 10013',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 13',
    ],
    [
        'ute_id' => 'sample_event_14',
        'name' => 'Sample Event 14',
        'date' => '2025-08-12',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '114 Sample St - - City - ST - 10014',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 14',
    ],
    [
        'ute_id' => 'sample_event_15',
        'name' => 'Sample Event 15',
        'date' => '2025-08-15',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '115 Sample St - - City - ST - 10015',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 15',
    ],
    [
        'ute_id' => 'sample_event_16',
        'name' => 'Sample Event 16',
        'date' => '2025-08-18',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '116 Sample St - - City - ST - 10016',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 16',
    ],
    [
        'ute_id' => 'sample_event_17',
        'name' => 'Sample Event 17',
        'date' => '2025-08-21',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '117 Sample St - - City - ST - 10017',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 17',
    ],
    [
        'ute_id' => 'sample_event_18',
        'name' => 'Sample Event 18',
        'date' => '2025-08-24',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '118 Sample St - - City - ST - 10018',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 18',
    ],
    [
        'ute_id' => 'sample_event_19',
        'name' => 'Sample Event 19',
        'date' => '2025-08-27',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '119 Sample St - - City - ST - 10019',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 19',
    ],
    [
        'ute_id' => 'sample_event_20',
        'name' => 'Sample Event 20',
        'date' => '2025-08-30',
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
        'address' => '120 Sample St - - City - ST - 10020',
        'type' => 'paid',
        'time' => '18:00|20:00',
        'venuename' => 'Event Venue 20',
    ],
];
