<?php
return [
    [
        'event_ute_id' => 'sample_event_1',
        'event_name' => 'Sample Event 1',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 1,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_2',
        'event_name' => 'Sample Event 2',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 2,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_3',
        'event_name' => 'Sample Event 3',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 3,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_4',
        'event_name' => 'Sample Event 4',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 4,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_5',
        'event_name' => 'Sample Event 5',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 5,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_6',
        'event_name' => 'Sample Event 6',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 6,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_7',
        'event_name' => 'Sample Event 7',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 7,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_8',
        'event_name' => 'Sample Event 8',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 8,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_9',
        'event_name' => 'Sample Event 9',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 9,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_10',
        'event_name' => 'Sample Event 10',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 10,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_11',
        'event_name' => 'Sample Event 11',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 11,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_12',
        'event_name' => 'Sample Event 12',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 12,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_13',
        'event_name' => 'Sample Event 13',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 13,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_14',
        'event_name' => 'Sample Event 14',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 14,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_15',
        'event_name' => 'Sample Event 15',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 15,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_16',
        'event_name' => 'Sample Event 16',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 16,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_17',
        'event_name' => 'Sample Event 17',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 17,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_18',
        'event_name' => 'Sample Event 18',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 18,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_19',
        'event_name' => 'Sample Event 19',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 19,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
    [
        'event_ute_id' => 'sample_event_20',
        'event_name' => 'Sample Event 20',
        'ticket_name' => 'General Admission',
        'waitlist_id' => 20,
        'ticketlimit' => 50,
        'baseeventcost' => 20.0,
        'discountedmembercost' => 15.0,
        'premiummembercost' => 10.0,
    ],
];
