<?php
return [
    [
        'ute_id' => 'sample_event_1',
        'name'   => 'Dinner at Crawleys',
        'date'   => '2025-07-01',
        'baseeventcost'        => 12.00,
        'discountedmembercost' => 10.00,
        'premiummembercost'    => 8.00,
        'address'              => '400 Sample Ave - - Richmond - Virginia - 23230',
        'type'                 => 'free',
        'time'                 => '18:00|20:00',
        'venuename'            => 'Crawleys Diner',
        'venueurl'             => 'https://example.com/crawleys',
        'url2'                 => 'https://yelp.com/crawleys',
        'url3'                 => 'https://facebook.com/crawleys',
        'url4'                 => 'https://instagram.com/crawleys',
        'mainimageid'          => 1,
        'otherimageids'        => '2,3',
        'waitlistavailable'    => 1,
        'all_day_event'        => 0,
        'virtual_event'        => 0,
        'refundsavailable'     => 1,
        'hosts'                => 'Alice,Bob',
        'volunteers'           => 'Carol',
        'discountcode'         => '{"code":"SAVE2","type":"flat","amount":2}',
        'created_at'           => '2025-06-01 10:00:00',
        'updated_at'           => '2025-06-01 10:00:00',
    ],
    [
        'ute_id' => 'sample_event_2',
        'name'   => 'Roller Skating',
        'date'   => '2025-07-10',
        'baseeventcost'        => 15.00,
        'discountedmembercost' => 12.00,
        'premiummembercost'    => 8.00,
        'address'              => '500 Sample St - - Richmond - Virginia - 23231',
        'type'                 => 'paid',
        'time'                 => '19:30|21:30',
        'venuename'            => 'Rollerdome',
        'venueurl'             => 'http://www.rollerdomeskating.com/',
        'url2'                 => 'https://facebook.com/RollerdomeSkating/',
        'url3'                 => 'https://yelp.com/biz/roller-dome-richmond',
        'url4'                 => 'https://instagram.com/rollerdome',
        'mainimageid'          => 4,
        'otherimageids'        => '5,6,7',
        'waitlistavailable'    => 1,
        'all_day_event'        => 0,
        'virtual_event'        => 0,
        'refundsavailable'     => 1,
        'hosts'                => 'Dave',
        'volunteers'           => 'Eve,Frank',
        'discountcode'         => '{"code":"2OffSpecial","type":"flat","amount":2}',
        'created_at'           => '2025-06-02 08:00:00',
        'updated_at'           => '2025-06-02 08:00:00',
    ],
    [
        'ute_id' => 'sample_event_3',
        'name'   => 'Buffet & Besties at King\'s Korner',
        'date'   => '2025-07-20',
        'baseeventcost'        => 0.00,
        'discountedmembercost' => 0.00,
        'premiummembercost'    => 0.00,
        'address'              => '7511 Airfield Dr - - North Chesterfield - Virginia - 23237',
        'type'                 => 'paid',
        'time'                 => '18:30|20:30',
        'venuename'            => 'King\'s Korner Catering and Restaurant',
        'venueurl'             => 'https://www.kingskornercatering.com/',
        'url2'                 => 'https://facebook.com/kingskornercatering/',
        'url3'                 => 'https://yelp.com/biz/kings-korner-catering-and-restaurant-north-chesterfield',
        'url4'                 => 'https://tripadvisor.com/Restaurant_Review-g60893-d395520',
        'mainimageid'          => 8,
        'otherimageids'        => '9,10,11,12',
        'waitlistavailable'    => 1,
        'all_day_event'        => 0,
        'virtual_event'        => 0,
        'refundsavailable'     => 0,
        'hosts'                => 'Grace',
        'volunteers'           => '',
        'discountcode'         => '',
        'created_at'           => '2025-06-03 09:00:00',
        'updated_at'           => '2025-06-03 09:00:00',
    ],
];
