<?php
$members = [
    [
        'first_name'             => 'Stacy',
        'last_name'              => 'Harper',
        'email'                 => 'tilypoquh@mailinator.com',
        'password'              => '##ALNEE#DLI)wZHvOp14A8Tp',
        'member_type'           => 'member',
        'membership_level'      => 'basic',
        'profileimgid'          => 0,
        'joined_at'             => date('Y-m-d H:i:s', strtotime('-60 days')),
        'address'               => '100 Example St - - Richmond - Virginia - 23230',
        'phone'                 => '804-555-0101',
        'dob'                   => '1990-05-01',
        'subscription_id'       => 'SUB1001',
        'subscription_status'   => 'active',
        'facebook'              => 'https://facebook.com/stacy.harper',
        'linkedin'              => 'https://linkedin.com/in/stacy.harper',
        'instagram'             => 'https://instagram.com/stacy.harper',
        'twitter'               => 'https://twitter.com/stacyharper',
        'biography'             => 'Stacy enjoys volunteering and connecting with new people.',
        'notes'                 => 'Sample admin notes for Stacy.',
        'interests'             => 'Music, Hiking',
        'opt_in_marketing_email'=> 1,
        'opt_in_marketing_sms'  => 0,
        'opt_in_event_email'    => 1,
        'opt_in_event_sms'      => 0,
        'hide_event_attendance' => 0,
    ],
    [
        'first_name'             => 'Tucker',
        'last_name'              => 'Copeland',
        'email'                 => 'sicuzymyt@mailinator.com',
        'password'              => '^$^^6@TyiDpiL72B3rZ7v*tY',
        'member_type'           => 'member',
        'membership_level'      => 'premium',
        'profileimgid'          => 0,
        'joined_at'             => date('Y-m-d H:i:s', strtotime('-55 days')),
        'address'               => '200 Example St - Apt 2 - Richmond - Virginia - 23231',
        'phone'                 => '804-555-0102',
        'dob'                   => '1991-07-04',
        'subscription_id'       => 'SUB1002',
        'subscription_status'   => 'active',
        'facebook'              => 'https://facebook.com/tucker.copeland',
        'linkedin'              => 'https://linkedin.com/in/tuckercopeland',
        'instagram'             => 'https://instagram.com/tucker.copeland',
        'twitter'               => 'https://twitter.com/tuckcopeland',
        'biography'             => 'Avid traveler and event enthusiast.',
        'notes'                 => 'Prefers SMS updates.',
        'interests'             => 'Travel, Cooking',
        'opt_in_marketing_email'=> 1,
        'opt_in_marketing_sms'  => 1,
        'opt_in_event_email'    => 1,
        'opt_in_event_sms'      => 1,
        'hide_event_attendance' => 0,
    ],
    [
        'first_name'             => 'Sam',
        'last_name'              => 'Lydard',
        'email'                 => 'tryingtoadultrva@gmail.com',
        'password'              => 'bNe#JO#h)uyP30oAdcZkrQfi',
        'member_type'           => 'super_admin',
        'membership_level'      => 'premium',
        'profileimgid'          => 0,
        'joined_at'             => date('Y-m-d H:i:s', strtotime('-90 days')),
        'address'               => '300 Example Ave - Suite 5 - Richmond - Virginia - 23233',
        'phone'                 => '804-555-0103',
        'dob'                   => '1985-02-12',
        'subscription_id'       => 'SUB1003',
        'subscription_status'   => 'active',
        'facebook'              => 'https://facebook.com/sam.lydard',
        'linkedin'              => 'https://linkedin.com/in/samlydard',
        'instagram'             => 'https://instagram.com/sam.lydard',
        'twitter'               => 'https://twitter.com/samlydard',
        'biography'             => 'Site administrator and event organizer.',
        'notes'                 => 'Has access to everything.',
        'interests'             => 'Tech, Music',
        'opt_in_marketing_email'=> 1,
        'opt_in_marketing_sms'  => 0,
        'opt_in_event_email'    => 1,
        'opt_in_event_sms'      => 0,
        'hide_event_attendance' => 0,
    ],
    [
        'first_name'             => 'Julie',
        'last_name'              => 'Marsh',
        'email'                 => 'eippih@gmail.com',
        'password'              => 'a14B%(T*UXk1auRFd)#ZNw)g',
        'member_type'           => 'super_admin',
        'membership_level'      => 'premium',
        'profileimgid'          => 0,
        'joined_at'             => date('Y-m-d H:i:s', strtotime('-85 days')),
        'address'               => '400 Example Blvd - - Richmond - Virginia - 23234',
        'phone'                 => '804-555-0104',
        'dob'                   => '1988-08-22',
        'subscription_id'       => 'SUB1004',
        'subscription_status'   => 'active',
        'facebook'              => 'https://facebook.com/julie.marsh',
        'linkedin'              => 'https://linkedin.com/in/juliemarsh',
        'instagram'             => 'https://instagram.com/julie.marsh',
        'twitter'               => 'https://twitter.com/juliemarsh',
        'biography'             => 'Helps coordinate volunteers and social outreach.',
        'notes'                 => '',
        'interests'             => 'Art, Fitness',
        'opt_in_marketing_email'=> 1,
        'opt_in_marketing_sms'  => 0,
        'opt_in_event_email'    => 1,
        'opt_in_event_sms'      => 0,
        'hide_event_attendance' => 0,
    ],
    [
        'first_name'             => 'Adam',
        'last_name'              => 'Peoples',
        'email'                 => 'foreunner1618@gmail.com',
        'password'              => '3grQTvBOODPRtOOQESmS0TXD',
        'member_type'           => 'admin',
        'membership_level'      => 'premium',
        'profileimgid'          => 0,
        'joined_at'             => date('Y-m-d H:i:s', strtotime('-70 days')),
        'address'               => '500 Example Cir - - Richmond - Virginia - 23235',
        'phone'                 => '804-555-0105',
        'dob'                   => '1992-11-30',
        'subscription_id'       => 'SUB1005',
        'subscription_status'   => 'active',
        'facebook'              => 'https://facebook.com/adam.peoples',
        'linkedin'              => 'https://linkedin.com/in/adampeoples',
        'instagram'             => 'https://instagram.com/adam.peoples',
        'twitter'               => 'https://twitter.com/adampeoples',
        'biography'             => 'Handles day to day admin tasks.',
        'notes'                 => '',
        'interests'             => 'Outdoors, Music',
        'opt_in_marketing_email'=> 1,
        'opt_in_marketing_sms'  => 0,
        'opt_in_event_email'    => 1,
        'opt_in_event_sms'      => 0,
        'hide_event_attendance' => 0,
    ],
    [
        'first_name'             => 'Mariah',
        'last_name'              => 'Payne',
        'email'                 => 'mariah.payne831@gmail.com',
        'password'              => '3grQTvBOODPRtOOQESmS0TXD',
        'member_type'           => 'admin',
        'membership_level'      => 'premium',
        'profileimgid'          => 0,
        'joined_at'             => date('Y-m-d H:i:s', strtotime('-68 days')),
        'address'               => '600 Example Rd - - Richmond - Virginia - 23236',
        'phone'                 => '804-555-0106',
        'dob'                   => '1993-03-15',
        'subscription_id'       => 'SUB1006',
        'subscription_status'   => 'active',
        'facebook'              => 'https://facebook.com/mariah.payne',
        'linkedin'              => 'https://linkedin.com/in/mariahpayne',
        'instagram'             => 'https://instagram.com/mariah.payne',
        'twitter'               => 'https://twitter.com/mariahpayne',
        'biography'             => 'Assists with admin and outreach.',
        'notes'                 => '',
        'interests'             => 'Cooking, Fitness',
        'opt_in_marketing_email'=> 1,
        'opt_in_marketing_sms'  => 0,
        'opt_in_event_email'    => 1,
        'opt_in_event_sms'      => 0,
        'hide_event_attendance' => 0,
    ],
    [
        'first_name'             => 'Cassidy',
        'last_name'              => 'Ryan',
        'email'                 => 'claineryan13@gmail.com',
        'password'              => '^yDYADcss&kcH29yxhdvnJXO',
        'member_type'           => 'volunteer',
        'membership_level'      => 'premium',
        'profileimgid'          => 0,
        'joined_at'             => date('Y-m-d H:i:s', strtotime('-45 days')),
        'address'               => '700 Example Way - - Richmond - Virginia - 23237',
        'phone'                 => '804-555-0107',
        'dob'                   => '1994-06-21',
        'subscription_id'       => 'SUB1007',
        'subscription_status'   => 'active',
        'facebook'              => 'https://facebook.com/cassidy.ryan',
        'linkedin'              => 'https://linkedin.com/in/cassidyryan',
        'instagram'             => 'https://instagram.com/cassidy.ryan',
        'twitter'               => 'https://twitter.com/cassidyryan',
        'biography'             => 'Regular volunteer at events.',
        'notes'                 => '',
        'interests'             => 'Volunteering, Music',
        'opt_in_marketing_email'=> 1,
        'opt_in_marketing_sms'  => 0,
        'opt_in_event_email'    => 1,
        'opt_in_event_sms'      => 0,
        'hide_event_attendance' => 0,
    ],
    [
        'first_name'             => 'Dana',
        'last_name'              => 'Harrell',
        'email'                 => 'dana.p.harrell@gmail.com',
        'password'              => 'b0niD@oMxf9wax@n8*@DIYGH',
        'member_type'           => 'volunteer',
        'membership_level'      => 'premium',
        'profileimgid'          => 0,
        'joined_at'             => date('Y-m-d H:i:s', strtotime('-40 days')),
        'address'               => '800 Example Pl - - Richmond - Virginia - 23238',
        'phone'                 => '804-555-0108',
        'dob'                   => '1995-12-08',
        'subscription_id'       => 'SUB1008',
        'subscription_status'   => 'active',
        'facebook'              => 'https://facebook.com/dana.harrell',
        'linkedin'              => 'https://linkedin.com/in/danaharrell',
        'instagram'             => 'https://instagram.com/dana.harrell',
        'twitter'               => 'https://twitter.com/danaharrell',
        'biography'             => 'Helps coordinate volunteers.',
        'notes'                 => '',
        'interests'             => 'Volunteering, Outdoors',
        'opt_in_marketing_email'=> 1,
        'opt_in_marketing_sms'  => 0,
        'opt_in_event_email'    => 1,
        'opt_in_event_sms'      => 0,
        'hide_event_attendance' => 0,
    ],
];

for ($i = 1; $i <= 10; $i++) {
    $members[] = [
        'first_name'            => 'Member' . $i,
        'last_name'             => 'Example',
        'email'                 => 'sample_member_' . $i . '@example.com',
        'password'              => 'password',
        'profileimgid'          => 0,
        'joined_at'             => date('Y-m-d H:i:s', strtotime('-' . ($i * 3) . ' days')),
        'address'               => $i . ' Main St - - Richmond - VA - 2323' . $i,
        'phone'                 => '555-000-' . sprintf('%04d', $i),
        'dob'                   => '1990-01-0' . (($i % 9) + 1),
        'member_type'           => 'member',
        'membership_level'      => ($i % 3 === 0) ? 'premium' : (($i % 2) ? 'basic' : 'free'),
        'subscription_id'       => 'SUB1' . str_pad( $i + 8, 3, '0', STR_PAD_LEFT ),
        'subscription_status'   => 'active',
        'facebook'              => 'https://facebook.com/member' . $i,
        'linkedin'              => 'https://linkedin.com/in/member' . $i,
        'instagram'             => 'https://instagram.com/member' . $i,
        'twitter'               => 'https://twitter.com/member' . $i,
        'biography'             => 'Sample biography for member ' . $i,
        'notes'                 => '',
        'interests'             => 'Music, Hiking',
        'opt_in_marketing_email'=> 1,
        'opt_in_marketing_sms'  => 0,
        'opt_in_event_email'    => 1,
        'opt_in_event_sms'      => 0,
        'hide_event_attendance' => 0,
        'banned_until'          => ($i % 4 === 0) ? date('Y-m-d H:i:s', strtotime('+30 days')) : null,
    ];
}

return $members;
